<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260512212148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Sync schema with JavaFX database';
    }

    public function up(Schema $schema): void
    {
        // Remove unused columns from document table
        $this->addSql('ALTER TABLE document DROP medicaments');
        $this->addSql('ALTER TABLE document DROP dosage_instructions');
        $this->addSql('ALTER TABLE document DROP duree');

        // Update dossier_medical - drop patient_id FK and index
        $this->addSql('ALTER TABLE dossier_medical DROP CONSTRAINT fk_3581ee626b899279');
        $this->addSql('DROP INDEX IF EXISTS uniq_3581ee626b899279');
        $this->addSql('ALTER TABLE dossier_medical DROP patient_id');
        $this->addSql('ALTER TABLE dossier_medical ALTER numero_dossier SET NOT NULL');
        $this->addSql('ALTER TABLE dossier_medical ALTER telephone TYPE VARCHAR(30)');

        // Update user table - make status and theme_preference NOT NULL
        $this->addSql('ALTER TABLE "user" ALTER status SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER theme_preference SET NOT NULL');

        // Update user_activity_log - fix identity
        $this->addSql('ALTER TABLE user_activity_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_activity_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user_activity_log ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE user_activity_log ALTER created_at SET NOT NULL');

        // Update appointment_rating - fix identity and constraints
        $this->addSql('ALTER TABLE appointment_rating DROP CONSTRAINT appointment_rating_appointment_id_fkey');
        $this->addSql('ALTER TABLE appointment_rating ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE appointment_rating ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE appointment_rating ALTER patient_id SET NOT NULL');
        $this->addSql('ALTER TABLE appointment_rating ALTER rated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE appointment_rating ALTER rated_at SET NOT NULL');
        $this->addSql('ALTER TABLE appointment_rating ADD CONSTRAINT FK_9FD7996CE5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment_rating ADD CONSTRAINT FK_9FD7996C6B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_9FD7996C6B899279 ON appointment_rating (patient_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE appointment_rating DROP CONSTRAINT FK_9FD7996CE5B533F9');
        $this->addSql('ALTER TABLE appointment_rating DROP CONSTRAINT FK_9FD7996C6B899279');
        $this->addSql('DROP INDEX IF EXISTS IDX_9FD7996C6B899279');
        $this->addSql('ALTER TABLE appointment_rating ALTER id SET DEFAULT nextval(\'appointment_rating_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE appointment_rating ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE appointment_rating ALTER rated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE appointment_rating ALTER rated_at DROP NOT NULL');
        $this->addSql('ALTER TABLE appointment_rating ALTER patient_id DROP NOT NULL');
        $this->addSql('ALTER TABLE appointment_rating ADD CONSTRAINT appointment_rating_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES appointment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "document" ADD medicaments TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE "document" ADD dosage_instructions TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE "document" ADD duree VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD patient_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ALTER numero_dossier DROP NOT NULL');
        $this->addSql('ALTER TABLE dossier_medical ALTER telephone TYPE VARCHAR(8)');
        $this->addSql('ALTER TABLE dossier_medical ADD CONSTRAINT fk_3581ee626b899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_3581ee626b899279 ON dossier_medical (patient_id)');
        $this->addSql('ALTER TABLE "user" ALTER status DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER theme_preference DROP NOT NULL');
        $this->addSql('ALTER TABLE user_activity_log ALTER id SET DEFAULT nextval(\'user_activity_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE user_activity_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE user_activity_log ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE user_activity_log ALTER created_at DROP NOT NULL');
    }
}