<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204213848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patient_caregiver (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, permissions VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, patient_id INT DEFAULT NULL, caregiver_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81220CFA6B899279 ON patient_caregiver (patient_id)');
        $this->addSql('CREATE INDEX IDX_81220CFA41946261 ON patient_caregiver (caregiver_id)');
        $this->addSql('ALTER TABLE patient_caregiver ADD CONSTRAINT FK_81220CFA6B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE patient_caregiver ADD CONSTRAINT FK_81220CFA41946261 FOREIGN KEY (caregiver_id) REFERENCES "user" (id)');
        $this->addSql('DROP TABLE doctor');
        $this->addSql('ALTER TABLE "user" ADD dtype VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD specialty VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD license_number VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD consultation_fee NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD average_rating NUMERIC(3, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD total_reviews INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD bio TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD profile_image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD is_verified BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD date_of_birth DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD relationship_type VARCHAR(50) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE doctor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, specialty VARCHAR(255) NOT NULL, license_number VARCHAR(50) NOT NULL, consultation_fee NUMERIC(10, 2) NOT NULL, average_rating NUMERIC(3, 2) NOT NULL, total_reviews INT NOT NULL, bio TEXT DEFAULT NULL, profile_image VARCHAR(255) DEFAULT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE patient_caregiver DROP CONSTRAINT FK_81220CFA6B899279');
        $this->addSql('ALTER TABLE patient_caregiver DROP CONSTRAINT FK_81220CFA41946261');
        $this->addSql('DROP TABLE patient_caregiver');
        $this->addSql('ALTER TABLE "user" DROP dtype');
        $this->addSql('ALTER TABLE "user" DROP specialty');
        $this->addSql('ALTER TABLE "user" DROP license_number');
        $this->addSql('ALTER TABLE "user" DROP consultation_fee');
        $this->addSql('ALTER TABLE "user" DROP average_rating');
        $this->addSql('ALTER TABLE "user" DROP total_reviews');
        $this->addSql('ALTER TABLE "user" DROP bio');
        $this->addSql('ALTER TABLE "user" DROP profile_image');
        $this->addSql('ALTER TABLE "user" DROP is_verified');
        $this->addSql('ALTER TABLE "user" DROP date_of_birth');
        $this->addSql('ALTER TABLE "user" DROP relationship_type');
    }
}
