<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217212055 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT fk_fe38f84487f4fb17');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT fk_fe38f8446b899279');
        $this->addSql('ALTER TABLE health_metric DROP CONSTRAINT fk_fc3cc6666b899279');
        $this->addSql('ALTER TABLE medical_document DROP CONSTRAINT fk_a4f367216b899279');
        $this->addSql('ALTER TABLE teleconsultation DROP CONSTRAINT fk_ce327b23e5b533f9');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE health_metric');
        $this->addSql('DROP TABLE medical_document');
        $this->addSql('DROP TABLE teleconsultation');
        $this->addSql('ALTER TABLE "user" ADD profile_picture VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, reason TEXT DEFAULT NULL, patient_id INT NOT NULL, doctor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_fe38f84487f4fb17 ON appointment (doctor_id)');
        $this->addSql('CREATE INDEX idx_fe38f8446b899279 ON appointment (patient_id)');
        $this->addSql('CREATE TABLE health_metric (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_fc3cc6666b899279 ON health_metric (patient_id)');
        $this->addSql('CREATE TABLE medical_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference_number VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_type VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a4f367216b899279 ON medical_document (patient_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_a4f367218bf1ae50 ON medical_document (reference_number)');
        $this->addSql('CREATE TABLE teleconsultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, video_link VARCHAR(500) NOT NULL, access_code VARCHAR(255) DEFAULT NULL, appointment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ce327b23e5b533f9 ON teleconsultation (appointment_id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT fk_fe38f84487f4fb17 FOREIGN KEY (doctor_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT fk_fe38f8446b899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE health_metric ADD CONSTRAINT fk_fc3cc6666b899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medical_document ADD CONSTRAINT fk_a4f367216b899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teleconsultation ADD CONSTRAINT fk_ce327b23e5b533f9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" DROP profile_picture');
    }
}
