<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217162142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE medical_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference_number VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_type VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4F367218BF1AE50 ON medical_document (reference_number)');
        $this->addSql('CREATE INDEX IDX_A4F367216B899279 ON medical_document (patient_id)');
        $this->addSql('ALTER TABLE medical_document ADD CONSTRAINT FK_A4F367216B899279 FOREIGN KEY (patient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE medical_document DROP CONSTRAINT FK_A4F367216B899279');
        $this->addSql('DROP TABLE medical_document');
    }
}
